#!/bin/bash
KVERSION="$(uname -r)"
set -x

./clean
make -C /lib/modules/$KVERSION/build M=$PWD modules
sudo rmmod snd-firewire-dice
sudo rmmod snd-firewire-003
sudo rmmod snd-firewire-lib
sudo rmmod snd-hwdep
sudo rmmod snd-pcm
sudo rmmod snd-seq-midi
sudo rmmod snd-seq-midi-event
sudo rmmod snd-seq
sudo rmmod snd-rawmidi
sudo rmmod snd-seq-device
sudo rmmod snd-timer
sudo rmmod snd
sudo rmmod soundcore
sudo rmmod snd-page-alloc
#sudo rmmod firewire-ohci
#sudo rmmod firewire-core
#sudo modprobe firewire-core
#sudo modprobe firewire-ohci
#sleep 2
sudo modprobe snd-page-alloc
sudo modprobe soundcore
sudo modprobe snd
sudo modprobe snd-timer
sudo modprobe snd-pcm
sudo modprobe snd_hwdep
sudo insmod ./snd-firewire-lib.ko
sudo insmod ./snd-firewire-003.ko
sleep 1
dmesg|tail
